### ISSUE TITLE
Release to Maven Central?

### ISSUE THREAD

**Issue by thc202** [spoofzu/DeepViolet#231]
Would be possible to have the artifacts released to Maven Central? It would be easier to consume/integrate the library into other projects.

**Comment by spoofzu** [comment]
This is a great suggestion.  In fact, I tried to do this around Nov/Dec 2016 but was not successful.  :o(  My IT admin kung fu is weak.  I have the Travis CI part working and building the code.  I have a few test cases running.  After I got that going I thought I could try and publish to mavencentral.  I requested a maven account.  However, I have not been successful publishing to mavencentral.  I had the travis build setup to build and run test cases on checkin.  When I add a release label I was trying to get it to also kick off a publish to mavencentral but I could not get it to work right.  I'm looking for some expertise to get mavencentral working for me.  Once it's working I can maintain it.

**Comment by spoofzu** [comment]
I have been a little distracted since my comment but I was finally successful publishing DV into the central repository.  The snapshot is published for now since I am still preparing DV for the BlackHat event this summer.  I consider this issue successfully closed.  See the wiki for details how to include DV in your Maven projects.  https://github.com/spoofzu/DeepViolet/wiki
